# Build Stage
FROM ghcr.io/evanrichter/cargo-fuzz:latest as builder

## Add source code to the build stage.
ADD . /src
WORKDIR /src

RUN echo building instrumented harnesses && \
    bash -c "pushd fuzz && cargo +nightly -Z sparse-registry fuzz build && popd" && \
    mv fuzz/target/x86_64-unknown-linux-gnu/release/parse /parse && \
    mv fuzz/target/x86_64-unknown-linux-gnu/release/queryselector /queryselector && \
    mv fuzz/target/x86_64-unknown-linux-gnu/release/parse_mut /parse_mut && \
    mv fuzz/target/x86_64-unknown-linux-gnu/release/find /find && \
    echo done

RUN echo building non-instrumented harnesses && \
    export RUSTFLAGS="--cfg fuzzing -Clink-dead-code -Cdebug-assertions -C codegen-units=1" && \
    bash -c "pushd fuzz && cargo +nightly -Z sparse-registry build --release && popd" && \
    mv fuzz/target/release/parse /parse_no_inst && \
    mv fuzz/target/release/queryselector /queryselector_no_inst && \
    mv fuzz/target/release/parse_mut /parse_mut_no_inst && \
    mv fuzz/target/release/find /find_no_inst && \
    echo done

# Package Stage
FROM rustlang/rust:nightly

COPY --from=builder /parse /parse_no_inst /
COPY --from=builder /queryselector /queryselector_no_inst /
COPY --from=builder /parse_mut /parse_mut_no_inst /
COPY --from=builder /find /find_no_inst /
